Added new PublicationStatus DRAFT_FOR_DELETION
BIBSYSDEV/nva-datamodel-java pull request #100
Opened 2020-12-15 08:17 UTC by janbj

2020-12-15 09:54 UTC, axthosarouris approved these changes

2020-12-15 11:50 UTC, janbj commented on src/main/java/no/unit/nva/model/PublicationStatus.java
> +    REJECTED("REJECTED"),
REJECTED is not a real status is it?

2020-12-16 07:02 UTC, brinxmat approved these changes

2020-12-16 08:53 UTC, axthosarouris requested changes
Requested change: Rurik's comment. expectedError.
The reset are suggestions.

2020-12-16 08:53 UTC, axthosarouris commented on src/main/java/no/unit/nva/model/Publication.java
> +    private void verifyStatusTransition(PublicationStatus nextStatus)
I think what Rurik suggests is clearer, also since we are using a map we should exploit its capabilities and not turn it into a list

2020-12-16 08:53 UTC, axthosarouris commented on src/main/java/no/unit/nva/model/PublicationStatus.java
> +    NEW("NEW"),
Do we use new anywhere?

2020-12-16 08:53 UTC, axthosarouris commented on src/test/java/no/unit/nva/PublicationTest.java
> +    void updateStatusForValidTransitionIsOk() throws Exception {
Can you parametrize the test to test all valid transitions?

example:
```
@ParameterizedTest
    @EnumSource(value= PublicationStatus.class, names = { "DRAFT_FOR_DELETION","PUBLISHED"  })
    void updateStatusForValidTransitionIsOk(PublicationStatus target) throws Exception {
        Publication publication = generatePublication(JOURNAL_ARTICLE);
        publication.setStatus(DRAFT);
        publication.updateStatus(target);

        assertThat(publication.getStatus(), is(equalTo(target)));
    }
```

2020-12-16 08:53 UTC, axthosarouris commented on src/test/java/no/unit/nva/PublicationTest.java
> +        String error = String.format(InvalidPublicationStatusTransitionException.ERROR_MSG_TEMPLATE,
expectedError

2020-12-16 11:02 UTC, axthosarouris approved these changes

2020-12-16 11:11 UTC, merged