Np 1979 doi request status parsing
BIBSYSDEV/nva-datamodel-java pull request #114
Opened 2021-01-25 10:58 UTC by axthosarouris

2021-01-25 11:06 UTC, brinxmat requested changes

2021-01-25 11:06 UTC, brinxmat commented on src/main/java/no/unit/nva/model/DoiRequestStatus.java
> +            if (status.name().toUpperCase(DEFAULT_LOCALE).equals(upperCased)) {
Probably status.name().equalsIgnoreCase(doiRequestStatus)

2021-01-25 11:14 UTC, brinxmat requested changes

2021-01-25 11:14 UTC, brinxmat commented on src/main/java/no/unit/nva/model/DoiRequestStatus.java
> +    public static final Locale DEFAULT_LOCALE = Locale.getDefault();
Unused

2021-01-27 09:24 UTC, janbj approved these changes

2021-01-27 18:26 UTC, merged