Np 3051 add unconfirmed publisher and publisher
BIBSYSDEV/nva-datamodel-java pull request #185
Opened 2021-09-03 06:22 UTC by brinxmat

- Adds UnconfirmedPublisher and Publisher
- Question: Best way to deal with old publisher String values?

2021-09-03 10:10 UTC, janbj submitted a review, later dismissed

2021-09-03 11:06 UTC, axthosarouris requested changes

2021-09-03 11:06 UTC, axthosarouris commented on src/main/java/no/unit/nva/model/contexttypes/Publisher.java
> +    public Publisher(@JsonProperty("id") URI id) {
`@JsonCreator`

2021-09-06 11:46 UTC, axthosarouris submitted a review, later dismissed

2021-09-06 13:04 UTC, axthosarouris approved these changes

2021-09-06 13:10 UTC, janbj approved these changes

2021-09-06 14:32 UTC, merged