NP-3204 Fix isbn validator.
BIBSYSDEV/nva-datamodel-java pull request #202
Opened 2021-10-01 12:12 UTC by Eirik-Eide-Saur

No idea why all the json files where included but they became modified one way or another, same goes for the schema.yaml file

2021-10-01 13:07 UTC, brinxmat approved these changes

2021-10-01 13:42 UTC, axthosarouris requested changes

2021-10-02 08:02 UTC, brinxmat requested changes

2021-10-02 08:02 UTC, brinxmat commented on nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Book.java
> +            .map(isbn -> isbn.replaceAll(ANYTHING_BUT_DIGITS_AND_X_REGEX, ""))
This is entirely wrong as we lose validation for ISBNs that are input manually. The correct approach here is to catch the validation error and resubmit without the ISBN if-and-only-if you really want to throw away data willy-nilly. The issue should really be fixed in the data source

2021-10-05 07:19 UTC, axthosarouris approved these changes

2021-10-05 07:20 UTC, merged