Add media
BIBSYSDEV/nva-datamodel-java pull request #221
Opened 2021-10-20 14:12 UTC by brinxmat

2021-10-20 15:14 UTC, elkebab commented on documentation/MediaInternet.json
> +        "type" : "MediaInternet",
![bilde](https://user-images.githubusercontent.com/6313468/138121096-66ddd66e-7bb9-47e4-9527-a176c3aee03a.png)

I skissene ser det ut som at det er tenkt annerledes, hvor `publicationInstance.type` er en av: 
- Dokumenter
- Intervju
- Programledelse
- Programdeltagelse

Mens `Mediumtype` som virker å være det samme som `publicationInstance.contentType` for bl.a. artikkel i tidsskrift og kapittel

2021-10-21 08:19 UTC, axthosarouris requested changes

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/Media.java
> +    @JsonProperty(PROGRAMME)
The  "programme" here is in a way connected to the associated publication instance.

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/media/AbstractMediaInstance.java
> +    private static final NullPages pages = new NullPages();
if many classes have this "NullPages" doesn't this mean that we have may two or more kinds of PublicationInstances? Those with Pages (printed?) and those without.

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/media/AbstractMediaInstance.java
> +        return pages;
return "NullPages.instance()" where instance() returns the one and only NullPages object (and the constructor of NullPages is private);

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/media/AbstractMediaInstance.java
> +        return pages;
You can deprecate the NullPages constructor for now :)

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/media/AbstractMediaInstance.java
> +    public abstract void setPages(NullPages pages);
this should be the exact opposite of abstract. it should be final. The decision of what one can do here has been set by the type of the input parameter

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/media/MediaProgrammeParticipation.java
> +
4 times setPages(NullPages) -> make a final method in the abstract class

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/test/java/no/unit/nva/PublicationMapperTest.java
> +        assertThat(json.has("type"), is(equalTo(true)));
we can avoid the generic assertThat(assertMyExpectation(),is(true)) here by using this:
https://github.com/spotify/java-hamcrest#json-matchers

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/test/java/no/unit/nva/model/util/PublicationGenerator.java
> +    private static PublicationInstance<NullPages> getProgrammeParticipation() {
It is time to create a RefenceGenerator and put this method in its own class.

2021-10-21 08:19 UTC, axthosarouris commented on nva-datamodel-java/src/test/java/no/unit/nva/model/util/PublicationGenerator.java
> +                           .withId(URI.create("https://link.to.cristin.example.org/123"))
comment: You can use randomUri() from testutils

2022-06-10 12:07 UTC, closed without merging