Move create publication request to resource service
BIBSYSDEV/nva-datamodel-java pull request #243
Opened 2021-12-10 14:19 UTC by axthosarouris

2021-12-10 14:20 UTC, brinxmat submitted a review, later dismissed

2021-12-13 09:33 UTC, brinxmat requested changes

2021-12-13 09:33 UTC, brinxmat commented on migration/src/test/resources/libs.versions.toml
> +nvaCommonsVersion = { strictly = '1.16.23' }
Use 1.16.24

2021-12-13 09:38 UTC, janbj approved these changes

2021-12-13 09:42 UTC, brinxmat approved these changes

2021-12-13 09:44 UTC, merged