Added new Data model ConferenceAbstract
BIBSYSDEV/nva-datamodel-java pull request #267
Opened 2022-05-02 13:42 UTC by RanjithTom

2022-05-02 14:44 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/journal/ConferenceAbstract.java
> +     * Creates an object that matches the Journal pattern, but throws an exception if peerReviewed is set to true.
Not informative comment. It does not describe what is a ConferenceAbstract.

2022-05-02 14:44 UTC, axthosarouris requested changes
see comment

2022-05-03 05:52 UTC, brinxmat submitted a review, later dismissed
Fix the code comment, otherwise OK — I still don't understand what this is actually supposed to represent, but I guess I'm not alone in this.

2022-05-04 07:25 UTC, axthosarouris approved these changes

2022-05-04 07:36 UTC, merged