Initial commit to datamodel media contribution.
BIBSYSDEV/nva-datamodel-java pull request #272
Opened 2022-05-12 09:44 UTC by RanjithTom

Currently the context only have 2 enums such as MediaSubType and MediaFormat. Need to add more fields and publication instances in coming commits

2022-05-12 19:46 UTC, axthosarouris requested changes
In future PRs, do not commit the json files because the PR is very heavy for the browser. Make the changes in the model, and then in another PR update the version and the json fles.

2022-05-12 19:46 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/media/MediaFormat.java
> +    MediaFormat(String value) {
it needs a @JsonCreator method . You should look how we implement other enums

2022-05-12 19:46 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/contexttypes/media/MediaSubType.java
> +    MediaSubType(String value) {
ditto

2022-05-12 19:46 UTC, axthosarouris commented on nva-datamodel-java/src/main/java/no/unit/nva/model/instancetypes/media/MediaBase.java
> +    public static final NullPages pages = new NullPages();
static values are capital, name it NULL_PAGES

2022-05-13 07:54 UTC, brinxmat reviewed
See other reviewer's comments

2022-06-08 14:07 UTC, merged