publication-knows-if-it-satisfies-findable-doi-requirements
BIBSYSDEV/nva-datamodel-java pull request #363
Opened 2023-03-29 13:28 UTC by anetteOlli

2023-03-29 13:30 UTC, anetteOlli commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +    public boolean satisfiesFindableDoiRequirements() {
Greit navn?

2023-03-29 13:31 UTC, anetteOlli commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +        return Optional.ofNullable(getEntityDescription())
Vurderte å hive alle disse metodene i en egen klasse med access protected. Hva tror du?

2023-03-29 13:34 UTC, anetteOlli commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +        return Optional.ofNullable(getEntityDescription())
altså klassen kunne være protected, med en metode protected boolean satisfiesFindableDoiRequirements og resten private

2023-03-29 14:59 UTC, brinxmat requested changes

2023-03-29 14:59 UTC, brinxmat commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +        Set.of(PublicationStatus.PUBLISHED, PUBLISHED_METADATA);
Static import for both?

2023-03-29 14:59 UTC, brinxmat commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +        return Optional.ofNullable(getEntityDescription())
Ja, jeg tror at det blir bedre

2023-03-29 14:59 UTC, brinxmat commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +    private boolean hasADate() {
`hasPublicationYear`

2023-03-30 08:23 UTC, anetteOlli commented on nva-datamodel-java/src/main/java/no/unit/nva/model/Publication.java
> +        Set.of(PublicationStatus.PUBLISHED, PUBLISHED_METADATA);
fikset

2023-03-31 07:28 UTC, brinxmat submitted a review, later dismissed

2023-03-31 08:39 UTC, merged