License data model to uri with validation.
BIBSYSDEV/nva-datamodel-java pull request #398
Opened 2023-06-01 06:46 UTC by EyobSikt

2023-06-01 13:19 UTC, ketilaa requested changes
Minor naming change requested, and I raised a question how we want to handle problems during migration.

2023-06-05 06:23 UTC, truhacevkir approved these changes

2023-06-09 06:21 UTC, ketilaa approved these changes

2023-06-09 06:21 UTC, truhacevkir approved these changes
Looks good

2023-06-09 06:21 UTC, truhacevkir commented on nva-datamodel-java/src/test/java/no/unit/nva/LicenseMigrationTest.java
> +    public static Stream<String> licenseProvider() {
fileWithLicenseProvider or fileProvider

2023-06-09 06:41 UTC, truhacevkir approved these changes

2023-06-09 06:42 UTC, merged