Np 45941 add unpublish comment
BIBSYSDEV/nva-datamodel-java pull request #460
Opened 2024-02-06 14:10 UTC by torbjokv

2024-02-06 14:43 UTC, anetteOlli approved these changes

2024-02-06 21:25 UTC, brinxmat requested changes
I'd change the name of the object to keep names short — otherwise merge away!

2024-02-06 21:25 UTC, brinxmat commented on nva-datamodel-java/src/main/java/no/unit/nva/model/PublicationUnpublishNote.java
> +public record PublicationUnpublishNote(String note) implements PublicationNoteBase {
`UnpublishingNote`?

2024-02-07 07:52 UTC, brinxmat approved these changes

2024-02-07 07:54 UTC, merged