Renamed doiRequest.date to doiRequest.createdDate
BIBSYSDEV/nva-datamodel-java pull request #86
Opened 2020-10-13 06:43 UTC by janbj

2020-10-13 07:42 UTC, axthosarouris submitted a review, later dismissed

2020-10-14 06:45 UTC, norrs approved these changes

2020-10-14 06:49 UTC, brinxmat approved these changes

2020-10-14 06:49 UTC, brinxmat commented on src/main/java/no/unit/nva/model/DoiRequest.java
> +    private Instant createdDate;
If we add `@JsonAlias("date")`, we avoid breaking the API

2020-10-14 08:41 UTC, norrs requested changes
Agree with  @brinxmat , fix the JsonAlias :+1:

2020-10-15 07:10 UTC, brinxmat reviewed
Accidentally clicked Approve, see change request

2020-10-15 07:11 UTC, brinxmat requested changes
Did it again

2020-10-16 07:03 UTC, norrs approved these changes

2020-10-16 14:13 UTC, axthosarouris approved these changes

2020-10-19 06:55 UTC, merged