Add Other
BIBSYSDEV/nva-datamodel-java pull request #88
Opened 2020-10-16 15:31 UTC by brinxmat

I think that this code will change, as I think the spec has changed

2020-10-27 11:57 UTC, sarahse commented on documentation/Other.json
> +        "linkedContext" : "https://example.org/linkedContext"
mangler `publisher`, `level` ++ her (fra kanalregister)

2020-10-27 11:57 UTC, sarahse commented on documentation/Other.json
> +          "end" : "23"
må ha mulighet til å registrere totalt antall sider også

2020-10-27 11:58 UTC, sarahse commented on documentation/Other.json
> +}
Det nevnes `Published in` på denne typen også: https://github.com/BIBSYSDEV/NVA-scenarios/pull/61/files 

Men det vet jeg ikke hva er...

2020-11-02 13:20 UTC, sarahse commented on documentation/OtherArticle.json
> +        "type" : "OtherSerial",
Er dette riktig type? Hvilken type er `OtherSerial`? det skal ikke være `JournalArticle` her?

2020-11-02 13:24 UTC, sarahse submitted a review, later dismissed
Ser ut som vi har de feltene vi trenger for å kunne lagre dataene til de to forskjellige typene 👍

2021-05-03 09:24 UTC, axthosarouris requested changes
Develop branch does not exist. Merge to main

2022-06-10 12:07 UTC, closed without merging